# Generated by Django 6.0.3 on 2026-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='department',
            table='tb_department',
        ),
    ]
